### ISSUE TITLE
Confusing parameter typing in dynamic filters

### ISSUE THREAD

**Issue by lthi747** [wsporto/typesql#24]
Types in parameters that are generated for dynamic filters are bit confusing

Example

```sql
SELECT 
  t.id,
  t.created_at
FROM taxonomy t
WHERE 
  (:filter1 IS TRUE AND t.id > 10)
  OR (:filter2 IS NOT NULL OR t.id < 200)
```

Produce ts like

```ts
export type BoolParamsParams = {
	filter1: undefined | null;
	filter2: undefined | null;
}
```

**Comment by wsporto** [comment]
Thanks for the report @lthi747, the fix should be in v0.10.5.
For this query TypeSQL should now produce:

```ts
export type BoolParamsParams = {
  filter1: boolean;
  filter2: any | null;
}
```
The filter2 param has the type `any` because it is not possible to infer it's type from this query.
